name: dart_meteor_web
description: This library make connection between meteor backend and flutter web app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 1.2.0
homepage: https://github.com/tanutapi/dart_meteor/tree/web

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  rxdart: ^0.27.4
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.21.3
  collection: ^1.16.0
