name: dart_meteor_web
description: This library make connection between meteor backend and flutter web app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 1.1.2
homepage: https://github.com/tanutapi/dart_meteor/tree/web

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  rxdart: ^0.27.3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
  collection: ^1.15.0
